export enum NotificationType {
  PROMOTIONAL = 'PROMOTIONAL',
  REMINDER = 'REMINDER',
  NEWS = 'NEWS',
  BEHAVIORAL = 'BEHAVIORAL',
  RESCHEDULE = 'RESCHEDULE',
  CANCELLATION = 'CANCELLATION',
  OTHER = 'OTHER',
}
