export enum RoleViewsEnum {
  EMPLOYEES = 'EMPLOYEES',
  ALL_VIEWS = 'ALL_VIEWS',
  APPOINTMENTS_DOCTOR = 'APPOINTMENTS_DOCTOR',
  PATIENTS = 'PATIENTS',
  DASHBOARD = 'DASHBOARD',
  APPOINTMENTS_PATIENT = 'APPOINTMENTS_PATIENT',
  CLINICS = 'CLINICS',
  MESSAGES = 'MESSAGES',
  RECORDS = 'RECORDS',
  COMMON = 'COMMON',
}
