export enum RoleViewsEnum {
  USER_PROFILE = 'USER_PROFILE',
  ALL_VIEWS = 'ALL_VIEWS',
  USER_APPOINTMENTS = 'USER_APPOINTMENTS',
  ADMIN_DASHBOARD = 'ADMIN_DASHBOARD',
  PATIENT_DASHBOARD = 'PATIENT_DASHBOARD',
  PATIENTS_APPOINTMENTS = 'PATIENTS_APPOINTMENTS',
}
